### ISSUE TITLE
[UPDATE] Attribute Price NOT appears on JWSTransactionDecodedPayload

### ISSUE THREAD

**Issue by ArnauKokoro** [apple/app-store-server-library-java#56] opened 2023-11-07 14:39 UTC
Hi,

Could you please release new version to JWSTransactionDecodedPayload have price.

Thanks!

**Comment by ruofeilyu** [comment] 2023-11-13 17:03
Very needed!

**Comment by ruofeilyu** [comment] 2023-11-13 17:11
Very needed!!

**Comment by alexanderjordanbaker** [comment] 2023-11-13 18:29
This was resolved in #53

**Closed by alexanderjordanbaker** 2023-11-13 18:29 UTC

**Comment by hankovich** [comment] 2023-12-14 20:44
@alexanderjordanbaker do you know why Store Server API stopped returning price and currency in their responses?
Several days ago all decoded transactions contained both `price` and `currency` fileds, but today I see that *all* responses come without these fields

**Comment by hankovich** [comment] 2023-12-16 13:17
It looks like it was a bug, the issue is resolved now, Apple returns price and currency as expected
