### ISSUE TITLE
How to call App Store Server API sandbox environment

### ISSUE THREAD

**Issue by sigriswil** [apple/app-store-server-library-java#92] opened 2024-05-01 09:53 UTC
I call transaction information for several apps. And I don't have environment information.

That's why I'm calling the sandbox environment as an official guide. However, unlike the official guide, certain apps sometimes use production URLs to call endpoints to receive 401 status codes and successfully call endpoints using the sandbox environment.

Why does this difference occur unlike the official guide?
Is there any way to determine if I should call into a sandbox environment when I receive a 401 status code from a production endpoint?

Sometimes it's a production transaction and JWT hasn't expired, but I'm getting a 401 status code response and calling it into a sandbox environment.

Please let me know the solution.

**Comment by hakusai22** [comment] 2024-05-01 13:01
> I call transaction information for several apps. And I don't have environment information.
> 
> That's why I'm calling the sandbox environment as an official guide. However, unlike the official guide, certain apps sometimes use production URLs to call endpoints to receive 401 status codes and successfully call endpoints using the sandbox environment.
> 
> Why does this difference occur unlike the official guide? Is there any way to determine if I should call into a sandbox environment when I receive a 401 status code from a production endpoint?
> 
> Sometimes it's a production transaction and JWT hasn't expired, but I'm getting a 401 status code response and calling it into a sandbox environment.
> 
> Please let me know the solution.

1. If you actively call the apple api to obtain information, you can first use the online configuration to request the transactionId to obtain relevant information. If the online configuration request returns TRANSACTION_ID_NOT_FOUND (4040010L), you can then use the sandbox environment configuration to request the information.
2. If you are receiving information from the callback address and are not sure whether it is sandbox or production, you can add parameters to the callback address, such as xxxx?issandbox=true.

**Comment by sigriswil** [comment] 2024-05-02 01:40
Hello. Thank you for your response.
May I know the meaning of the 'issandbox' parameter?
I don't know the environment, so what criteria should I write the value?
Currently, the 'Get Transaction Info' API does not have the corresponding parameters written.
Do I call it like the example below?
ex) https://api.storekit.itunes.apple.com/inApps/v1/transactions/1234567890?issandbox=false

What I want to know is that when I receive a 401 status code in response from a production environment endpoint, I want to know if this status code is a real error or if I have to call it into a sandbox environment.

**Comment by hakusai22** [comment] 2024-05-02 02:38
> Hello. Thank you for your response. May I know the meaning of the 'issandbox' parameter? I don't know the environment, so what criteria should I write the value? Currently, the 'Get Transaction Info' API does not have the corresponding parameters written. Do I call it like the example below? ex) https://api.storekit.itunes.apple.com/inApps/v1/transactions/1234567890?issandbox=false
> 
> **What I want to know is that when I receive a 401 status code in response from a production environment endpoint, I want to know if this status code is a real error or if I have to call it into a sandbox environment.**
> 
> If the production environment endpoint needs to receive a 401 status code and call it to the sandbox, we have confirmed that the response header of the production environment endpoint contains keys 'b3' and 'apple-tk'. Should I check for the presence or absence of a heading key?

1. This library has already encapsulated the relevant requests for you, why do you still need to request this link yourself? You can refer to this https://github.com/apple/app-store-server-library-java/issues/76
2. The issandbox I am talking about is the App Store server notification, which probably has nothing to do with you.

**Comment by sigriswil** [comment] 2024-05-02 08:10
> > Hello. Thank you for your response. May I know the meaning of the 'issandbox' parameter? I don't know the environment, so what criteria should I write the value? Currently, the 'Get Transaction Info' API does not have the corresponding parameters written. Do I call it like the example below? ex) https://api.storekit.itunes.apple.com/inApps/v1/transactions/1234567890?issandbox=false
> > **What I want to know is that when I receive a 401 status code in response from a production environment endpoint, I want to know if this status code is a real error or if I have to call it into a sandbox environment.**
> > If the production environment endpoint needs to receive a 401 status code and call it to the sandbox, we have confirmed that the response header of the production environment endpoint contains keys 'b3' and 'apple-tk'. Should I check for the presence or absence of a heading key?
> 
> 1. This library has already encapsulated the relevant requests for you, why do you still need to request this link yourself? You can refer to this [I only have one transactionId, but I’m not sure whether it’s a sandbox or a production environment. How to get the subscription plan? #76](https://github.com/apple/app-store-server-library-java/issues/76)
> 2. The issandbox I am talking about is the App Store server notification, which probably has nothing to do with you.

I already know how to call the sandbox environment when the TRANSSACTION_ID_NOT_FOUND response occurs.

The question is, if it's a sandbox payment, when you call a production environment endpoint to get a response with a 401 status code and call a sandbox environment endpoint to succeed.

I was wondering if it was a real error when I received the 401 status code from the production environment endpoint, or in what case should I call it into the sandbox environment.

**Comment by hakusai22** [comment] 2024-05-02 08:18
> 1. TRANSACTION_ID_NOT_FOUND

Now in my company, TRANSACTION_ID_NOT_FOUND appears online and then calls the sandbox environment. There is no other good way for the time being.

**Comment by hakusai22** [comment] 2024-05-02 08:18
> > > Hello. Thank you for your response. May I know the meaning of the 'issandbox' parameter? I don't know the environment, so what criteria should I write the value? Currently, the 'Get Transaction Info' API does not have the corresponding parameters written. Do I call it like the example below? ex) https://api.storekit.itunes.apple.com/inApps/v1/transactions/1234567890?issandbox=false
> > > **What I want to know is that when I receive a 401 status code in response from a production environment endpoint, I want to know if this status code is a real error or if I have to call it into a sandbox environment.**
> > > If the production environment endpoint needs to receive a 401 status code and call it to the sandbox, we have confirmed that the response header of the production environment endpoint contains keys 'b3' and 'apple-tk'. Should I check for the presence or absence of a heading key?
> > 
> > 
> > 
> > 1. This library has already encapsulated the relevant requests for you, why do you still need to request this link yourself? You can refer to this [I only have one transactionId, but I’m not sure whether it’s a sandbox or a production environment. How to get the subscription plan? #76](https://github.com/apple/app-store-server-library-java/issues/76)
> > 2. The issandbox I am talking about is the App Store server notification, which probably has nothing to do with you.
> 
> I already know how to call the sandbox environment when the TRANSSACTION_ID_NOT_FOUND response occurs.
> 
> The question is, if it's a sandbox payment, when you call a production environment endpoint to get a response with a 401 status code and call a sandbox environment endpoint to succeed.
> 
> I was wondering if it was a real error when I received the 401 status code from the production environment endpoint, or in what case should I call it into the sandbox environment.

Now in my company, TRANSACTION_ID_NOT_FOUND appears online and then calls the sandbox environment. There is no other good way for the time being.

**Comment by alexanderjordanbaker** [comment] 2024-05-04 00:33
@sigriswil If you don't have a production release of the app, you are not allowed to use the production App Store Server API. Once you release an app for the first time in production, then you will be able to receive a TRANSSACTION_ID_NOT_FOUND exception

**Comment by sigriswil** [comment] 2024-05-04 10:06
> @sigriswil If you don't have a production release of the app, you are not allowed to use the production App Store Server API. Once you release an app for the first time in production, then you will be able to receive a TRANSSACTION_ID_NOT_FOUND exception

Thank you for your answer. We manage multiple app information and don't know if the apps have a production release. Even if there is a production release, the token hasn't expired, and very occasionally returns a 401 response for unknown reasons. Is there a way to know if it's an actual 401 error, or a 401 error because there's no production release?

**Comment by hakusai22** [comment] 2024-05-04 10:17
> 
Is this the scene?
https://github.com/apple/app-store-server-library-java/issues/96

**Comment by hakusai22** [comment] 2024-05-04 10:18
> > @sigriswil If you don't have a production release of the app, you are not allowed to use the production App Store Server API. Once you release an app for the first time in production, then you will be able to receive a TRANSSACTION_ID_NOT_FOUND exception
> 
> Thank you for your answer. We manage multiple app information and don't know if the apps have a production release. Even if there is a production release, the token hasn't expired, and very occasionally returns a 401 response for unknown reasons. Is there a way to know if it's an actual 401 error, or a 401 error because there's no production release?

Is this the scene? [https://github.com/apple/app-store-server-library-java/issues/96](https://github.com/apple/app-store-server-library-java/issues/96)

**Comment by sigriswil** [comment] 2024-05-04 11:14
> > > @sigriswil If you don't have a production release of the app, you are not allowed to use the production App Store Server API. Once you release an app for the first time in production, then you will be able to receive a TRANSSACTION_ID_NOT_FOUND exception
> > 
> > 
> > Thank you for your answer. We manage multiple app information and don't know if the apps have a production release. Even if there is a production release, the token hasn't expired, and very occasionally returns a 401 response for unknown reasons. Is there a way to know if it's an actual 401 error, or a 401 error because there's no production release?
> 
> Is this the scene? (httpStatusCode=401, apiError=null, apiErrorMessage='null') #96

Yes. I happen in the 'Get Transaction Info' API.

**Comment by alexanderjordanbaker** [comment] 2024-06-06 05:23
The issue appears to have changed into a duplicate of https://github.com/apple/app-store-server-library-java/issues/96, closing this issue in favor of that issue

**Closed by alexanderjordanbaker** 2024-06-06 05:23 UTC
